name: CD

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build, Test, and Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/setup-node@v1
        with:
          always-auth: true
          node-version: 12.x
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - uses: actions/checkout@v2
      - name: Restore Dependency Cache
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-dependency-cache-${{ hashFiles('**/package.json') }}
      - run: npm install
      - run: npm run bootstrap
      - run: npm run publish:ci -- --yes
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIT_AUTHOR_NAME: Ionitron
          GIT_AUTHOR_EMAIL: hi@ionicframework.com
          GIT_COMMITTER_NAME: Ionitron
          GIT_COMMITTER_EMAIL: hi@ionicframework.com
